import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'dist');
const origin='https://www.garten24h.de';
const e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const regions=[
['oberkraemer','Oberkrämer','Bötzow, Marwitz, Eichstädt, Bärenklau, Vehlefanz, Schwante und Neu-Vehlefanz','nord'],
['boetzow','Bötzow','Marwitz, Hennigsdorf und Schönwalde-Glien','nord'],['marwitz','Marwitz','Bötzow, Eichstädt und Velten','nord'],['eichstaedt','Eichstädt','Marwitz, Bärenklau und Vehlefanz','nord'],['baerenklau','Bärenklau','Eichstädt, Velten und Leegebruch','nord'],['vehlefanz','Vehlefanz','Schwante, Bärenklau und Neu-Vehlefanz','nord'],['schwante','Schwante','Vehlefanz, Sommerswalde und Kremmen','nord'],['neu-vehlefanz','Neu-Vehlefanz','Vehlefanz, Oberkrämer und Kremmen','nord'],
['hennigsdorf','Hennigsdorf','Nieder Neuendorf, Stolpe-Süd und Velten','nord'],['velten','Velten','Leegebruch, Hennigsdorf und Oberkrämer','nord'],['oranienburg','Oranienburg','Lehnitz, Sachsenhausen und Leegebruch','nord'],['hohen-neuendorf','Hohen Neuendorf','Bergfelde, Borgsdorf, Stolpe und Birkenwerder','nord'],['muehlenbecker-land','Mühlenbecker Land','Mühlenbeck, Schildow, Schönfließ und Zühlsdorf','nord'],['wandlitz','Wandlitz','Basdorf, Klosterfelde, Schönwalde, Schönerlinde und Stolzenhagen','nord'],
['schoenwalde-glien','Schönwalde-Glien','Schönwalde-Siedlung, Schönwalde-Dorf, Pausin, Perwenitz, Paaren im Glien, Wansdorf und Grünefeld','west'],['falkensee','Falkensee','Finkenkrug, Seegefeld und Falkenhagen','west'],['brieselang','Brieselang','Bredow, Zeestow und Nauen','west'],['dallgow-doeberitz','Dallgow-Döberitz','Dallgow, Döberitz und Seeburg','west'],['potsdam','Potsdam','Babelsberg, Bornstedt, Eiche und Groß Glienicke','west'],['teltow','Teltow','Ruhlsdorf, Kleinmachnow und Stahnsdorf','west'],['kleinmachnow','Kleinmachnow','Teltow, Stahnsdorf und Berlin-Zehlendorf','west'],['stahnsdorf','Stahnsdorf','Güterfelde, Sputendorf und Schenkenhorst','west'],['nuthetal','Nuthetal','Bergholz-Rehbrücke, Saarmund und Fahlhorst','west'],
['grossbeeren','Großbeeren','Diedersdorf, Heinersdorf und Kleinbeeren','sued'],['ludwigsfelde','Ludwigsfelde','Genshagen, Siethen und Ahrensdorf','sued'],['blankenfelde-mahlow','Blankenfelde-Mahlow','Blankenfelde, Mahlow, Dahlewitz, Groß Kienitz und Jühnsdorf','sued'],['rangsdorf','Rangsdorf','Groß Machnow und Klein Kienitz','sued'],['schoenefeld','Schönefeld','Großziethen, Waßmannsdorf, Selchow, Kiekebusch und Waltersdorf','sued'],['grossziethen','Großziethen','Kleinziethen, Schönefeld und Berlin-Rudow','sued'],['wassmannsdorf','Waßmannsdorf','Schönefeld, Selchow und Großziethen','sued'],['selchow','Selchow','Waßmannsdorf, Schönefeld und Rotberg','sued'],['kiekebusch','Kiekebusch','Karlshof, Waltersdorf und Rotberg','sued'],['waltersdorf','Waltersdorf','Schulzendorf, Schönefeld und Kiekebusch','sued'],['schulzendorf','Schulzendorf','Eichwalde, Zeuthen und Waltersdorf','sued'],['zeuthen','Zeuthen','Eichwalde, Miersdorf und Wildau','sued'],['koenigs-wusterhausen','Königs Wusterhausen','Niederlehme, Senzig, Zernsdorf und Wernsdorf','sued'],
['ahrensfelde','Ahrensfelde','Eiche, Blumberg, Lindenberg und Mehrow','ost'],['bernau','Bernau bei Berlin','Schönow, Ladeburg und Panketal','ost'],['hoppegarten','Hoppegarten','Hönow, Dahlwitz-Hoppegarten und Münchehofe','ost'],['neuenhagen','Neuenhagen bei Berlin','Fredersdorf-Vogelsdorf, Altlandsberg und Bruchmühle','ost'],['petershagen-eggersdorf','Petershagen/Eggersdorf','Fredersdorf, Strausberg und Bruchmühle','ost'],['schoeneiche','Schöneiche bei Berlin','Woltersdorf, Rahnsdorf und Münchehofe','ost'],['ruedersdorf','Rüdersdorf bei Berlin','Hennickendorf, Herzfelde, Lichtenow und Tasdorf','ost'],['erkner','Erkner','Woltersdorf, Gosen-Neu Zittau und Grünheide','ost'],
['berlin','Berlin','Pankow, Reinickendorf, Spandau, Charlottenburg-Wilmersdorf, Steglitz-Zehlendorf, Tempelhof-Schöneberg, Neukölln, Treptow-Köpenick, Marzahn-Hellersdorf, Lichtenberg, Friedrichshain-Kreuzberg und Mitte','berlin'],['berlin-ost','Berlin Ost','Kaulsdorf, Mahlsdorf, Biesdorf, Hellersdorf, Marzahn, Lichtenberg, Pankow und Treptow-Köpenick','berlin'],['kaulsdorf','Berlin-Kaulsdorf','Mahlsdorf, Biesdorf und Hellersdorf','berlin'],['mahlsdorf','Berlin-Mahlsdorf','Kaulsdorf, Hönow und Hoppegarten','berlin'],['biesdorf','Berlin-Biesdorf','Kaulsdorf, Marzahn und Karlshorst','berlin'],['marzahn-hellersdorf','Berlin Marzahn-Hellersdorf','Marzahn, Hellersdorf, Biesdorf, Kaulsdorf und Mahlsdorf','berlin'],['lichtenberg','Berlin-Lichtenberg','Karlshorst, Friedrichsfelde und Hohenschönhausen','berlin'],['pankow','Berlin-Pankow','Buch, Karow, Blankenburg, Französisch Buchholz und Niederschönhausen','berlin'],['treptow-koepenick','Berlin Treptow-Köpenick','Köpenick, Friedrichshagen, Rahnsdorf, Müggelheim, Grünau, Bohnsdorf und Altglienicke','berlin'],['reinickendorf','Berlin-Reinickendorf','Tegel, Heiligensee, Hermsdorf, Frohnau und Waidmannslust','berlin'],['spandau','Berlin-Spandau','Staaken, Gatow, Kladow und Hakenfelde','berlin'],['steglitz-zehlendorf','Berlin Steglitz-Zehlendorf','Lichterfelde, Lankwitz, Dahlem, Nikolassee und Wannsee','berlin'],['neukoelln','Berlin-Neukölln','Britz, Buckow, Rudow und Gropiusstadt','berlin'],['tempelhof-schoeneberg','Berlin Tempelhof-Schöneberg','Tempelhof, Mariendorf, Marienfelde und Lichtenrade','berlin']
];
const groups={berlin:'Berlin & östliche Ortsteile',nord:'Oberkrämer & nördliches Umland',west:'Westliches Umland',sued:'Südliches Umland bis Schönefeld',ost:'Östliches Umland'};
const contexts={nord:['Baumbestand und Arbeitsbereich zusammen betrachten','Stehen mehrere Bäume auf einem Grundstück, muss nicht jeder gleich behandelt werden. Für die Einschätzung unterscheiden wir erhaltenswerte Kronen, abgestorbene Äste und Bäume, bei denen eine Fällung geprüft werden soll. Geben Sie bitte an, ob Zufahrten, Nebengebäude oder Nachbargrundstücke den Arbeitsbereich begrenzen.'],west:['Platz für kontrollierte Baumarbeiten schaffen','Zwischen Haus, Terrasse und Grundstücksgrenze fehlt häufig Platz für eine Fällung am Stück. Fotos aus mehreren Richtungen helfen, den verfügbaren Arbeitsraum einzuschätzen. Auch der Weg vom Baum bis zur Straße ist wichtig: Tore, Stufen und schmale Durchgänge beeinflussen die Planung.'],sued:['Zufahrt und Abtransport früh abstimmen','Für ein nachvollziehbares Angebot zählt nicht nur die Höhe des Baumes. Teilen Sie uns mit, wo Fahrzeuge stehen können, wie breit die Zufahrt ist und ob Äste und Stammholz auf dem Grundstück bleiben sollen. So lassen sich Baumarbeiten und das anschließende Aufräumen gemeinsam planen.'],ost:['Bäume im genutzten Garten erhalten und pflegen','Wo Garten, Haus und Baumbestand zusammenkommen, geht es oft um einzelne trockene Äste, ausladende Kronen oder einen Baum dicht am Gebäude. Beschreiben Sie das konkrete Problem: Soll Totholz entfernt, die Krone gepflegt oder eine Fällung geprüft werden? Daraus ergibt sich die passende Bestandsaufnahme.'],berlin:['Baumarbeiten mit Blick auf Nachbarn und Gebäude','Auf einem Berliner Grundstück sind Arbeitsbereich und Zugang besonders wichtige Angaben für die Planung. Bitte nennen Sie enge Durchgänge, parkende Fahrzeuge, angrenzende Gehwege und Gebäude in Baumnähe. Bei gemeinschaftlich genutzten Flächen klären wir auch, wer den Termin und den Zugang abstimmt.']};
const cta=(place='',label='Baumarbeiten anfragen')=>`<a class="btn primary" href="/kontakt?leistung=Baumarbeiten&amp;ort=${encodeURIComponent(place)}">${label}</a>`;
const pic=(i,alt,cls='')=>`<img class="${cls}" src="/assets/baumarbeiten/baumarbeiten-${i}.webp" alt="${alt}" width="${i===3?938:938}" height="${i===3?708:1252}" loading="lazy" decoding="async">`;
const directory=()=>`<section class="tree-directory section" id="regionen"><span class="eyebrow">Unser Einsatzgebiet</span><h2>Baumarbeiten in Ihrer Nähe.</h2><p>Von Oberkrämer über das westliche und südliche Umland bis Schönefeld – und in Berlin sowie im östlichen Umland. Wählen Sie Ihren Ort. Kleinere Ortsteile und Nachbarorte finden Sie auf den jeweiligen Seiten. Termine stimmen wir nach Standort und Umfang ab.</p><div class="tree-regions">${Object.entries(groups).map(([g,n])=>`<div><h3>${n}</h3>${regions.filter(r=>r[3]===g).map(r=>`<a href="/baumarbeiten-${r[0]}">${r[1]}</a>`).join('')}</div>`).join('')}</div></section>`;
const faqs=name=>[
[`Welche Baumarbeiten kann ich in ${name} anfragen?`,'Sie können Baumfällung, Baumpflege, Kronenpflege und die Entfernung von Totholz anfragen. Welche Maßnahme sinnvoll und vor Ort umsetzbar ist, klären wir anhand Ihrer Angaben und bei Bedarf bei einem Termin.'],
['Was kostet eine Baumfällung?','Der Aufwand hängt unter anderem von Höhe, Stammstärke, Zustand, Zugänglichkeit und Arbeitsraum ab. Auch die abschnittsweise Abtragung und der gewünschte Abtransport beeinflussen das Angebot. Deshalb nennen wir einen Preis nach Einschätzung Ihres Baumes.'],
['Welche Angaben brauchen Sie für ein Angebot?','Hilfreich sind Ort und Postleitzahl, Anzahl der Bäume, geschätzte Höhe, Fotos von Baum und Umgebung sowie Angaben zur Zufahrt. Beschreiben Sie die gewünschte Maßnahme und ob Schnittgut und Stammholz abgefahren werden sollen. Fotos können Sie Ihrer E-Mail hinzufügen.'],
['Darf ein Baum im Herbst einfach gefällt werden?','Der Herbst ist ein guter Zeitpunkt, um Baumarbeiten zu planen, aber keine pauschale Fällerlaubnis. Vor der Ausführung sind der Schutzstatus, mögliche Genehmigungen und der Artenschutz zu klären. In Berlin ist bei geschützten Bäumen das zuständige Umwelt- und Naturschutzamt Ansprechpartner; im Umland gelten die jeweiligen örtlichen Vorgaben.'],
['Muss ein Baum mit trockenen Ästen gefällt werden?','Nicht unbedingt. Ob eine gezielte Totholzentfernung oder Kronenpflege ausreicht, hängt vom Zustand des gesamten Baumes ab. Eine Einschätzung vor Ort hilft, zwischen einer Pflegemaßnahme und einer erforderlichen Fällung zu unterscheiden.']];
const services=`<section class="section tree-services"><span class="eyebrow">Rund um Ihren Baum</span><h2>Erhalten, pflegen oder sicher entfernen.</h2><div class="tree-cards"><article><span>01</span><h3>Baumfällung</h3><p>Wenn ein Baum entfernt werden muss, planen wir das Vorgehen passend zu Standort, Zustand und Platzverhältnissen. Bei beengten Bereichen wird eine abschnittsweise Abtragung geprüft.</p></article><article><span>02</span><h3>Totholzentfernung</h3><p>Abgestorbene Äste über Wegen, Sitzplätzen oder Stellflächen sollten beurteilt werden. Wir klären, welche Äste entfernt werden müssen und wie sich der Arbeitsbereich absichern lässt.</p></article><article><span>03</span><h3>Baum- & Kronenpflege</h3><p>Eine Pflegemaßnahme richtet sich nach Baumart, Zustand und Entwicklungsziel. Gemeinsam besprechen wir, welche Eingriffe sinnvoll sind, um den Baum zu erhalten.</p></article><article><span>04</span><h3>Aufräumen & Abtransport</h3><p>Ob Schnittgut und Stammholz vor Ort bleiben oder abgefahren werden sollen, stimmen wir im Angebot ab. So ist vor Arbeitsbeginn klar, was zur gewünschten Leistung gehört.</p></article></div></section>`;
let template=fs.readFileSync(path.join(root,'index.html'),'utf8');
const header=template.slice(template.indexOf('<body>')+6,template.indexOf('<main'));
const footer=template.slice(template.indexOf('</main>')+7);
function render(name,slug,nearby,zone){
 const main=!slug;const route=main?'/baumarbeiten':`/baumarbeiten-${slug}`;const title=main?'Baumarbeiten, Baumfällung & Baumpflege | Garten24h':`Baumfällung & Baumpflege ${name} | Garten24h`;
 const desc=`Baumarbeiten in ${name}: Baumfällung, Totholzentfernung und Kronenpflege. Garten24h prüft Ihr Vorhaben. Jetzt mit Standort und Fotos anfragen.`;
 const f=faqs(name);const context=contexts[zone]||contexts.ost;
 const schemas=[{'@context':'https://schema.org','@type':'Service',name:`Baumarbeiten in ${name}`,serviceType:['Baumfällung','Baumpflege','Totholzentfernung'],areaServed:{'@type':'Place',name},provider:{'@id':`${origin}/#business`},url:origin+route},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[['Start','/'],['Baumarbeiten','/baumarbeiten'],...(!main?[[name,route]]:[])].map(([n,u],i)=>({'@type':'ListItem',position:i+1,name:n,item:origin+u}))},{'@context':'https://schema.org','@type':'FAQPage',mainEntity:f.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}];
 let head=template.slice(0,template.indexOf('<body>')).replace(/<title>.*?<\/title>/,`<title>${e(title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${e(desc)}">`).replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${origin}${route}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${e(title)}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${e(desc)}">`).replace(/<meta property="og:image" content="[^"]*">/,`<meta property="og:image" content="${origin}/assets/baumarbeiten/baumarbeiten-3.webp">`).replace(/<script type="application\/ld\+json">[^<]*"@type":"FAQPage"[^<]*<\/script>/g,'').replace('</head>',schemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s)}</script>`).join('')+'</head>');
 const related=regions.filter(r=>r[3]===zone&&r[0]!==slug).slice(0,9);
 const body=`<section class="tree-hero"><div><nav class="tree-breadcrumb" aria-label="Brotkrümelnavigation"><a href="/">Start</a> / <a href="/baumarbeiten">Baumarbeiten</a>${!main?' / '+name:''}</nav><span class="eyebrow">Baumpflege · Fällung · Totholzentfernung</span><h1>${main?'Zeit, sich um Ihre Bäume zu kümmern.':`Baumarbeiten in ${name}.`}</h1><p>${main?'Jetzt Baumarbeiten für Herbst und Winter planen: Garten24h ist Ihr Ansprechpartner für Baumfällung, Baumpflege und Totholzentfernung in Berlin und Brandenburg.':`Sie möchten in ${name} einen Baum fällen lassen, trockene Äste entfernen oder Ihre Bäume pflegen lassen? Garten24h bespricht mit Ihnen die passende Maßnahme und plant die Umsetzung nach Prüfung des Standorts.`}</p><div class="actions">${cta(main?'':name)}<a class="tree-phone" href="tel:+493055283241">030 552 83 241</a></div><p class="tree-small">Standort und Fotos senden · Vorgehen abstimmen · Angebot erhalten</p></div><figure>${pic(main?4:3,'Baumarbeiten mit Seilklettertechnik am Stamm')}<figcaption>Einblicke in Baumarbeiten – Originalfotos aus der Praxis</figcaption></figure></section>
 ${services}
 <section class="section tree-story">${pic(2,'Baumarbeiter mit Kletterausrüstung am Baum')}<div><span class="eyebrow">${main?'Vor der Ausführung':e(name)+' & Umgebung'}</span><h2>${context[0]}</h2><p>${context[1]}</p><p>${main?'Ob einzelner Baum am Haus oder mehrere Bäume auf einer größeren Fläche: Wir stimmen den Arbeitsumfang mit Ihnen ab.':`Für Anfragen aus ${name} berücksichtigen wir auch das Umfeld von ${nearby}. Nennen Sie bitte den genauen Ortsteil und die Grundstücksadresse, damit wir Anfahrt und Vor-Ort-Termin sinnvoll abstimmen können.`}</p><p>Unser Ansprechpartner sitzt in Berlin-Kaulsdorf. Die genannten Orte sind Einsatzgebiete, keine zusätzlichen Niederlassungen.</p>${cta(main?'':name,'Mein Vorhaben besprechen')}</div></section>
 <section class="tree-band"><div><span class="eyebrow light">Herbst & Winter planen</span><h2>Trockene Äste? Ein Baum zu nah am Haus?</h2><p>Schicken Sie uns den Standort, Fotos und eine kurze Beschreibung. Wir klären den nächsten Schritt mit Ihnen.</p></div>${cta(main?'':name,'Anfrage starten')}</section>
 <section class="section"><span class="eyebrow">So geht es weiter</span><h2>In vier Schritten zu Ihren Baumarbeiten.</h2><div class="tree-cards"><article><span>01</span><h3>Baum beschreiben</h3><p>Ort, Anzahl, ungefähre Höhe und Fotos von Baum und Umgebung übermitteln.</p></article><article><span>02</span><h3>Standort prüfen</h3><p>Zugang, Arbeitsbereich, Zustand und erforderliche Voraussetzungen gemeinsam klären.</p></article><article><span>03</span><h3>Angebot abstimmen</h3><p>Maßnahmen, Termin und den Umgang mit Schnittgut und Stammholz festlegen.</p></article><article><span>04</span><h3>Arbeiten ausführen</h3><p>Nach Klärung der Voraussetzungen die vereinbarten Baumarbeiten umsetzen.</p></article></div></section>
 ${main?`<section class="section"><span class="eyebrow">Einblicke aus der Praxis</span><h2>Baumarbeiten in Bildern.</h2><div class="tree-gallery">${[1,3,5,6].map(i=>`<figure>${pic(i,i===6?'Arbeiten am unteren Stamm eines Baumes':'Baumarbeiten und abschnittsweise Abtragung mit Kletterausrüstung')}</figure>`).join('')}</div></section>`:''}
 <section class="section faqsection"><div><span class="eyebrow">Gut vorbereitet</span><h2>Fragen zu Baumarbeiten${main?'':' in '+name}.</h2><p>Jeder Baum und jedes Grundstück ist anders. Diese Angaben helfen bei der ersten Einschätzung.</p></div><div class="faq">${f.map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></section>
 ${main?directory():`<section class="section tree-near"><h2>Auch in Ihrer Umgebung erreichbar.</h2><p>Baumarbeiten im Umfeld von ${nearby} können Sie ebenfalls bei uns anfragen.</p><div>${related.map(r=>`<a href="/baumarbeiten-${r[0]}">${r[1]}</a>`).join('')}<a href="/baumarbeiten#regionen">Alle Einsatzgebiete</a></div></section>`}
 <section class="tree-band"><div><h2>${main?'Jetzt Baumarbeiten anfragen.':`Ihr Baumprojekt in ${name}.`}</h2><p>Eine kurze Beschreibung genügt für den ersten Kontakt. Fotos können Sie direkt Ihrer E-Mail hinzufügen.</p></div><div class="actions">${cta(main?'':name)}<a class="tree-phone" href="tel:+493055283241">Direkt anrufen</a></div></section>`;
 return head+'<body>'+header+'<main id="content">'+body+'</main>'+footer;
}
for(const [slug,name,nearby,zone] of regions){const dir=path.join(root,`baumarbeiten-${slug}`);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),render(name,slug,nearby,zone));}
const main=render('Berlin und Brandenburg','','','ost');fs.mkdirSync(path.join(root,'baumarbeiten'),{recursive:true});fs.writeFileSync(path.join(root,'baumarbeiten/index.html'),main);fs.writeFileSync(path.join(root,'baumarbeiten.html'),main);
let home=template;
if(!home.includes('id="baumarbeiten-saison"'))home=home.replace('<section class="section home-intro">',`<section class="tree-season section" id="baumarbeiten-saison"><figure>${pic(4,'Baumarbeiter bei der abschnittsweisen Abtragung eines Baumes')}</figure><div><span class="eyebrow">Jetzt für Herbst & Winter anfragen</span><h2>Starke Bäume.<br>Ein gutes Gefühl.</h2><p>Abgestorbene Äste, eine ausladende Krone oder ein Baum, der entfernt werden muss? Wir kümmern uns um Baumarbeiten in Berlin und Brandenburg – von der gezielten Pflege bis zur geplanten Fällung.</p><ul class="tree-tags"><li>Baumfällung</li><li>Totholzentfernung</li><li>Baum- & Kronenpflege</li></ul><div class="actions">${cta()}<a class="textlink" href="/baumarbeiten">Mehr erfahren</a></div><p class="tree-small">Auch im Umland: von Oberkrämer bis Schönefeld.</p></div></section><section class="section home-intro">`);
home=home.replace('Automatische Bewässerungsanlagen, Poolbau und moderne Gartentechnik – persönlich geplant, fachgerecht installiert und zuverlässig betreut.','Baumarbeiten, automatische Bewässerungsanlagen, Poolbau und moderne Gartentechnik – persönlich geplant, fachgerecht umgesetzt und zuverlässig betreut.');
home=home.replace(/<title>.*?<\/title>/,'<title>Garten24h | Baumarbeiten, Bewässerung & Poolbau Berlin</title>').replace(/<meta name="description" content="[^"]*">/,'<meta name="description" content="Baumfällung, Baumpflege und Totholzentfernung in Berlin und Brandenburg. Garten24h: auch Bewässerungsanlagen, Poolbau und Gartentechnik. Jetzt anfragen.">');
fs.writeFileSync(path.join(root,'index.html'),home);
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(d,x.name)):[path.join(d,x.name)]);}
for(const file of walk(root).filter(f=>f.endsWith('.html'))){let h=fs.readFileSync(file,'utf8');if(!h.includes('href="/trees.css"'))h=h.replace('</head>','<link rel="stylesheet" href="/trees.css"></head>');h=h.replace('<a class="tree-nav" href="/baumarbeiten">Baumarbeiten</a>','');if(!h.includes('class="tree-footer-link"'))h=h.replace('<h3>Schwerpunkte</h3>','<h3>Schwerpunkte</h3><a class="tree-footer-link" href="/baumarbeiten">Baumarbeiten & regionale Einsatzgebiete</a>');if(!h.includes('<option>Baumarbeiten</option>'))h=h.replace('<option>Andere Gartenleistung</option>','<option>Baumarbeiten</option><option>Andere Gartenleistung</option>');fs.writeFileSync(file,h);}
let sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');for(const [slug] of regions){const u=origin+'/baumarbeiten-'+slug;if(!sitemap.includes(`<loc>${u}</loc>`))sitemap=sitemap.replace('</urlset>',`<url><loc>${u}</loc><lastmod>2026-10-02</lastmod></url></urlset>`);}fs.writeFileSync(path.join(root,'sitemap.xml'),sitemap);
console.log(`Tree pages: ${regions.length} regional pages plus main service page; homepage and navigation updated.`);
